#!/usr/bin/env python
from PIL import Image
import glob, os, sys, getopt

currentDir = os.getcwd()

# The location of the images to be resized
imageDir = sys.argv[1]

# Get the desired width from the first argument
width = int(sys.argv[2])

# The name of the output directory
outputDir = sys.argv[3] + "/"

# Make the output directory
os.mkdir(outputDir)

for i in glob.glob(imageDir + "/*.jpg"):
	img = Image.open(i)
	height = width * img.size[1] / img.size[0]
	name = os.path.splitext(i)[0]
	fileType = os.path.splitext(i)[1]
	rsz = img.resize((width,height))
	rsz.save(outputDir + name + fileType)
	print(name + " resized...")

print(" ")
print("------------------------------------")
print("Resize completed! :)")
print("------------------------------------")
print(" ")
